### PR TITLE
Action bridge

### PR DESCRIPTION
**Pull request by v-lopez**

### CODE REVIEW

**Comment by v-lopez** [comment]
@ipa-hsd Would you like to review, and if approved, merge this here, or should I open a new PR to https://github.com/ros2/ros1_bridge

**Comment by hsd-dev** [comment]
@v-lopez I am currently reviewing it.

**Comment by v-lopez** [comment]
Thanks, I just pushed some changes that might have fixed the compilation in foxy.

I was building on rolling and the action client API had changed.

**Comment by hsd-dev** [comment]
makes sense why I was having build issues and was not generating the interfaces anymore. When I made the PR it was successfully generating the interfaces and the bridge worked well. Thanks for the effort.

**Comment by v-lopez** [comment]
No problem.

There's still one more issue there, I just started a foxy docker and will try to fix it. Apologies for the confusion.

**Comment by v-lopez** [comment]
Should be ready now, let me know if you have any issues, I was able to build on foxy and rolling.

**Comment by hsd-dev** [comment]
did you build the bridge against `Foxy` ? Dirk says it should be the master https://github.com/ros2/ros1_bridge/pull/256#issuecomment-631768990. I am using the [lastSuccessfulBuild](https://ci.ros2.org/view/packaging/job/packaging_linux/lastSuccessfulBuild/artifact/ws/ros2-package-linux-x86_64.tar.bz2)

**Comment by v-lopez** [comment]
rolling are debians made from most recent changes, maybe master from a few days/weeks ago. Did you have any issues?

**Comment by hsd-dev** [comment]
silly of me. I was just trying to avoid building ROS2 from source and still get the latest version. Will try the master.  
https://index.ros.org//doc/ros2/Installation/Maintaining-a-Source-Checkout/#latest-development-branches

**Comment by hsd-dev** [comment]
I finally had to build it against [lastSuccessfulBuild](https://ci.ros2.org/view/packaging/job/packaging_linux/lastSuccessfulBuild/artifact/ws/ros2-package-linux-x86_64.tar.bz2) since the master branches have compile errors. Your version of `action_bridge` compiles successfully now but most of the generated action interfaces are empty.

> @ipa-hsd [ipa-hsd#1](https://github.com/ipa-hsd/ros1_bridge/pull/1) fixes build issues for me, and I get both ROS1 -> ROS2 and ROS2 -> ROS1 communication.

Which action interface did you test it for?

**Comment by v-lopez** [comment]
I tried with the tf msgs and control_msgs.

Which ones are missing?

**Comment by hsd-dev** [comment]
alright I installed `control_msgs` for `Foxy` and now it looks good. Ready to be merged!

**Comment by ipa-hsd** [comment]
@v-lopez not sure if you had to `signoff` the commit because I am unable to do it from my side. https://github.com/ros2/ros1_bridge/pull/256/checks?check_run_id=1417453709

**Pull request merged**
